"""initial schema

Revision ID: 8974c06de62a
Revises: 
Create Date: 2025-12-22 19:46:26.388146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8974c06de62a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.CheckConstraint('duration >= 1 AND duration <= 600', name='duration_constraint'),
    sa.CheckConstraint('price > 0', name='price_constraint'),
    sa.CheckConstraint('rating >= 0 and rating <= 10', name='rating_constraint'),
    sa.CheckConstraint('year >= 1880 and year <= 2030', name='year_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_genre'), 'movies', ['genre'], unique=False)
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_is_watched'), 'movies', ['is_watched'], unique=False)
    op.create_index(op.f('ix_movies_price'), 'movies', ['price'], unique=False)
    op.create_index(op.f('ix_movies_rating'), 'movies', ['rating'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_rating'), table_name='movies')
    op.drop_index(op.f('ix_movies_price'), table_name='movies')
    op.drop_index(op.f('ix_movies_is_watched'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_genre'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
