"""ajustes en users

Revision ID: bf720d7c7278
Revises: 1e30b293fd70
Create Date: 2025-12-31 11:40:21.473632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf720d7c7278'
down_revision: Union[str, Sequence[str], None] = '1e30b293fd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('genres', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('genres', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('genres', 'modificated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'last_name')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.alter_column('genres', 'modificated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('genres', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('genres', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
